Issue #5 and #6 write and test global and local installation instructions.
Traap/tlc-article pull request #21
Opened 2017-01-10 07:02 UTC by Traap

This pull-request is to confirm the installation section of GettingStarted.pdf is adequate.
[GettingStarted.pdf](https://github.com/Traap/tlc-article/files/695443/GettingStarted.pdf)

2017-01-10 22:38 UTC, dlewissandy commented
You may want to make sure that the following prerequisites are mentioned in an appropriate location:
* Github authentication relies upon ssh-agent for authentication.   It should be running.
* You must have added your ssh key using the ssh-key command (e.g. ssh-key foo_key).   You can tell if you have a key configured by typing ssh-key -l

2017-01-10 22:40 UTC, dlewissandy commented
You may want to mention that the install directories can be looked up using

_kpswhich -var-value TEXMFLOCAL_

or 

_kpswhich -var-value TEXMFHOME_

2017-01-10 22:56 UTC, dlewissandy commented on GettingStarted.tex
> +  \item mkdir \tlcGlobalDist
On linux, you must pass the -p parameter to create a nested subdirectory.

e.g. sudo mkdir -p $(kpsewhich -var-value TEXMFLOCAL)/tex/latex/tlc-article

2017-01-10 23:04 UTC, dlewissandy requested changes

2017-01-10 23:04 UTC, dlewissandy commented on GettingStarted.tex
> +  \item cp -v \tlcProduct.cls \tlcGlobalDist/.
This command may require elevated permission

2017-01-10 23:04 UTC, dlewissandy commented on GettingStarted.tex
> +\end{enumerate}
can you add a verification step.   When I type 

find `kpsewhich --var-value TEXMFDIST` --name *.cls  

I do not see the new class listed.

2017-01-11 20:10 UTC, Traap commented
@dlewissandy I addressed each recommendation you made.  I also tested the implementation on my Linux Mint installation.  

[GettingStarted.pdf](https://github.com/Traap/tlc-article/files/699923/GettingStarted.pdf)

2017-01-12 04:13 UTC, dlewissandy approved these changes

2017-01-12 16:16 UTC, merged